JeffersonLab/hps-mc

scripts/print_mvn_project_version.py
tools/stdhep-lib/src/src/inc/stdhep_mcfio.h
tools/stdhep-lib/src/src/stdhep/stdhep_mcfio.c
tools/stdhep-tools/CMakeLists.txt
tools/stdhep-tools/src/Makefile
tools/stdhep-tools/src/random_sample.cc
tools/stdhep-tools/src/random_sample_usingInputEventsInOrder.cc
tools/stdhep-tools/src/stdhep_mcfio.h
tools/stdhep-tools/src/stdhep_util.cpp

1) Issue for a memory leak. This was causing issues running on large files.
2) Issue with fie open not returning the number of events properly.
3) Issue of random_sample.cc - 
i) random_sample.cc reads in all the input into a vector. This takes a lot of memory.
ii) random_sample.cc picks the input events at random. This means that an estimate of 37% input events are not used, and 37% are used more than once.
a) Solution1: random_sample_usingInputEventsInOrder.cc  – Just takes the events in order, avoiding the memory issue and the usage issue.
b) Solution2: Update of random_sample.cc  – Use the std::shuffle to randomize the order of the events. No waste of electrons, and less memory use.

Iss143: Fixed some issues in stdhep tools:

---

CMakeLists.txt
python/hpsmc/tools.py

Supports offline conditions db usage as implemented in
https://github.com/JeffersonLab/hps-java/pull/322
That should be merged before this.
Adds option to JobManager and FilterMCBunches for using offline conditions db:
```
job_manager.use_offline_conditions_db = True
```
Tested that this works now for filtering and readout using a build of hps-java from iss320 branch.
When building hps-mc, you will have to type in a github username and password during the build procedures to download the hps-conditions-backup project (it is private and only accessible to HPS collaboration members).

Updates to support offline conditions db usage

---

python/hpsmc/component.py
python/hpsmc/config.py
python/hpsmc/generators.py
python/hpsmc/job.py
python/hpsmc/tools.py

- Update to use ConfigParser instead of configparser
- Add method to Component for loading from alternate config section name
- Change some log messages during setup and config to debug level from info
- Fix wildcard copying in MG for generated LHE file names (makes wildcard more generic)
- Add an `-s` switch to Job for specifying job steps (was none before - same as `--job-steps`)
- Do not copy input files when running in dry run mode

Update to use ConfigParser

---

python/hpsmc/tools.py
python/jobs/hpstr_job.py

This PR adds support for the hpstr tool.
Tested with this sample job.json file:
```
{
"run_mode": 0,
"input_files": ["/work/slac/data/tritrigv2-beamv6_2500kBunches_HPS-PhysicsRun2016-Pass2_v4_5_0_pairs1_135.slcio"],
"output_files": ["events.root"],
"output_dir": "output",
"nevents": 100
}
```
Ran sample hps-mc job using:
```
python python/jobs/hpstr_job.py -c .hpsmc ./job.json
```
hpstr requires the following config to be set:
```
[HPSTR]
hpstr_install_dir = /work/slac/hpstr/install
hpstr_base = /work/slac/hpstr
```
...where `hpstr_install_dir` points to the installation directory and `hpstr_base` points to the project directory.
The python config must be present in the `processors/config` dir of the `hpstr_base` directory.
The `nevents` argument to hpstr is not supported for now as …

Iss145: Add preliminary support for hpstr

---

examples/tritrig_gen/job.json
generators/madgraph5/src/BH/SubProcesses/makefile
generators/madgraph5/src/BH/bin/generate_events
generators/madgraph5/src/BREM_soCalledWabs_forHPS/SubProcesses/makefile
generators/madgraph5/src/BREM_soCalledWabs_forHPS/bin/generate_events
generators/madgraph5/src/HPS_RadiativeTridents/SubProcesses/makefile
generators/madgraph5/src/HPS_RadiativeTridents/bin/generate_events
generators/madgraph5/src/HPS_soCalledBH/SubProcesses/makefile
generators/madgraph5/src/HPS_soCalledBH/bin/generate_events
generators/madgraph5/src/RAD/SubProcesses/makefile
generators/madgraph5/src/RAD/bin/generate_events
generators/madgraph5/src/simp/SubProcesses/makefile
generators/madgraph5/src/simp/bin/generate_events
generators/madgraph5/src/tritrig/SubProcesses/makefile
generators/madgraph5/src/tritrig/bin/generate_events

- Update the fortran flags in Madgraph to use `-std=legacy` so the compilation works with recent GCC releases
- Use `python2` instead of `python` in script execution for Python 3 compatibility (hps-mc builds with Python 3 only, now)

Update Madgraph fortran flags and call python2 instead of python

---

examples/beam_gen/.hpsmc
examples/beam_gen/job.json
examples/beam_gen/job.json.tmpl
examples/beam_gen/mkjobs.sh
examples/beam_gen/run.sh
examples/beam_gen/run_slurm.sh
examples/beam_gen/vars.json
python/hpsmc/batch.py
python/hpsmc/generators.py

Added Slurm to batch.py so we can now submit jobs via Slurm. There are a few ways to accomplish this, since Slurm has job array submission built in, one can submit individual jobs via hps-mc or one can write a script to do all the jobs by first letting hps-mc generate the job command first.

Slurm batch submission

---

tools/stdhep-tools/src/beam_coords.cc

In the tool beam_coords, particles and vertex are firstly rotated around x, then around y. However, inputs of the second rotation are original variable values, instead of variable values after the first rotation. 
For 2016 MC, rotation angle around x is calculated and set as -0.33 mrad. It is very close to 0, so the issue causes very slight effect on 2016 MC. Fortunate!

Iss255: fix issue about rotation in the tool beam_coords

---

generators/madgraph5/src/simp/Cards/me5_configuration.txt

Path in me5_configuration.txt exists on some systems used by HPS. Permission error crashes software. Changed path to non-existent path, so default config file path is used.

changed default path to MG5 config file

---

python/hpsmc/__init__.py

On Linux, the default is 16 kB in older versions, increases to 64 kB probably at python 3.8, but still too small to play nice with Lustre filesystem at JLab.  Here we increase it to 1 MB.  Note, this is only effective as of python 3.8.  If we need to use an older python version, then to increase shutil's buffer size requires using shutil.copyfileobj everywhere with an explicit buffer size argument.

Increase shutil copy buffer size

---

python/hpsmc/job_template.py

Fix a bug in job_template.py.
The bug causes that input file(s) from previous item is included by list of next item.

fix a bug in job_template.py

---

python/hpsmc/job.py

In a chain, input file list of current step  is mandatorily set as output from last step. However, we need to set specified inputs for some components. The PR fixes this issue.

fix an issue for setup of input file list of components

---

scripts/jlab-env.csh.in

Resolves #294
Load the modules necessary for running hps-mc at JLab using Swif.

Load modules for JLab environment

---

python/jobs/signal_beam_merge_to_recon_2016_job.py

For 2016 MC, filter is different from 2019 MC. This job script is for signal-beam merging of 2016 MC with SLIC files as inputs.

add a job script for 2016 MC

---

README.md
format_python_code.sh

I messed up somewhere again, but this should now be the actually working command to not change the comment style.

adjust command to fix comment style

---

python/hpsmc/job.py

This does a quick byte-by-byte comparison between the original output file in the run directory with the copy in the output directory to make sure that the copy didn't end early due to network-related filesystem issues.
I found this issue when scaling up hps-java jobs that produced mille binary data files. Two out of the 200 files produced were only partially copied to the output directory and no errors were reported in the log. I only found this out by comparing the originals in the scratch directory with the supposed copies in the output directory.
We _could_ make this optional, but a non-hierarchical comparison is so fast relative to the length of a job that I think we should leave it on all the time.

add check to output file copying

---

python/hpsmc/component.py
python/hpsmc/job.py
python/hpsmc/tools.py

Configure fieldmap location and setup the symlink in the ```Job``` class instead of individual components, where it was heavily duplicated. 
If a custom location is needed then use this new configuration in ```Job``` rather than individual components:
```
[Job]
hps_fieldmaps_dir = /path/to/my/fieldmaps
``` 
I tested these changes with ```examples/tritrig_slic_full_chain```, and both SLIC and Java-based components seem to work fine with it.
This includes the changes from [this PR](https://github.com/JeffersonLab/hps-mc/pull/359) so it should be approved/merged first. Or it can be closed without merging if this one is merged instead.

Improve fieldmap setup

---

python/hpsmc/batch.py

the '-l' argument to the hps-mc-job run subcommand does not exist anymore due to the updates to the logging infrastructure in 
https://github.com/JeffersonLab/hps-mc/pull/354

patch batch to align with updating logging

---

python/hpsmc/alignment/_apply.py
python/hpsmc/alignment/_parameter.py
python/hpsmc/alignment/_pattern.py
python/hpsmc/batch.py
python/hpsmc/job.py
python/jobs/pede_job.py
scripts/hps-mc-construct-detector.in

this is necessary because the 2016 parameter mapping had a few typos in it when making the assignments which breaks the translation from ID number to layer number and Ax/St
Because the 2016 parameter mapping does not follow the convention set by the later 2019+ mapping allowing for simple arithmetic to calculate the layer number from the last two digits of the ID, I have switched the layer-number-deduction to simply extract it from the parameter name as it appears in the mapping. Similarly, I switched to deducing axial/stereo by looking for those words in the name rather than trying to deduce it from the ID.
Besides this necessary change, I also added a few more cosmetic updates.
- Add a new line when writing a note to a detector README to keep the notes spaced out.
- Convert all …

deduce layer number and Ax/St from sensor name

---

python/hpsmc/batch.py
python/hpsmc/job.py

These are changes to core hps-mc classes that were mixed into the unrelated PR #364 . They should be reverted, put onto a separate branch, and tested independently for verification. Specifically, the Auger, LSF, and Slurm batch bindings need to be verified to work properly with one or more examples.

Revert changes to core classes that need to be tested

---

examples/idm/job.json
examples/idm/vars.json

According to [this table on confluence](https://confluence.slac.stanford.edu/display/hpsg/MC+Run+Numbers), valid run numbers for 2016 MC are 7000-8999 (inclusive). This search was motivated by the fact that the current run number 1162300 causes the readout java job to error-out after unsuccessfully attempting to retrieve conditions.

patch run number for 2016 MC

---

python/hpsmc/batch.py

The baseline jobs we were sending with swif2 had a number of issues in batch.py. Namely the script was changed so you had to use a fixed environment, and a few of the sys.argv calls were imcompatible with the new way of doing things. Furthermore there were properties of the Swif class that now had different names. We have uncovered all such errors preventing atleast the running of baselines on ifarm.

I love biscuits and gravy. Also I fixed some stuff jeremy did.

---

python/hpsmc/tools.py

As pointed out here: https://github.com/slaclab/slic/issues/101 , the particle table (when loaded) can cause excessive printouts for certain simulation samples without any observed benefit. This PR introduces a new optional parameter for the `SLIC` hps-mc component allowing users to disable the loading of the particle table if they so wish. The default is still to load the particle table in order to avoid breaking any current configurations (although I strongly suspect loading the particle table has no effect on any of the samples HPS is studying).

add slic parameter to disable particle table

---

python/hpsmc/job.py

The update is to add an option for cleanup of jobs.
With the update, the issue #426 for jobs by swif2 will be fixed by the following setting in [Job] by a configuration file:
```
enable_copy_output_files = False
enable_cleanup = False
```
The update has been tested. Job for test is successful.

add an option for cleanup of jobs

---

python/hpsmc/component.py
python/hpsmc/tools.py
python/jobs/data_cnv_10_percent_job.py

This is a fixed the previous improper pull request for SQLite: https://github.com/JeffersonLab/hps-mc/pull/428#
I modified the tools.py to add the class named SQLiteProc to copy a local SQLite snapshot that is saved on my jlab ifarm location: /w/hallb-scshelf2102/hps/zshi/swiftjob/SQLite/LocalTest/hps_conditions_2025_03_06.sqlite. I also added the workflow named data_cnv_10_percent_job.py for a workflow to submit this swif2 jobs. Only 3 files in total are modifed. 
This pull request is in response to the JIRA ticket for SQLite on SLAC confluence: https://jira.slac.stanford.edu/login-interim.jsp?os_destination=%2Fbrowse%2FHPSANA-56&permissionViolation=true

New Updated for SQLite Local Copying for 10% Production

---

python/hpsmc/tools.py

Just remove the comments on .hpsmc setup to make the codes look neater.

Remove Long Comments for .hpsmc Setup
