JeffersonLab/hps-mc

python/hpsmc/generators.py, python/test/mg4_test.py
- Make an "Events" dir so files are copied properly by MG
- Allow StdHepConverter to accept gzipped LHE files
=> Improve handling of MG4 output

python/hpsmc/base.py, python/hpsmc/generators.py, python/test/job_test.py
=> Set rand seed in MG run cards and add seed as arg to base Component class

generators/madgraph5/src/BH/Cards/me5_configuration.txt, generators/madgraph5/src/BREM_soCalledWabs_forHPS/Cards/me5_configuration.txt, generators/madgraph5/src/HPS_RadiativeTridents/Cards/me5_configuration.txt, generators/madgraph5/src/HPS_soCalledBH/Cards/me5_configuration.txt, generators/madgraph5/src/RAD/Cards/me5_configuration.txt, generators/madgraph5/src/tritrig/Cards/me5_configuration.txt, python/hpsmc/base.py, python/hpsmc/generators.py, python/hpsmc/tools.py, python/jobs/tritrig_job.py, tools/stdhep-tools/src/Makefile
Resolves #43, #38, #40 and #32.
=> Add tritrig job script and resolve a number of other issues

CMakeLists.txt, python/hpsmc/tools.py, python/test/job_test.py, scripts/hps-mc-env.sh.in
=> Add python wrappers for LCIO tools

python/hpsmc/batch.py, python/hpsmc/batch_ganga.py, python/hpsmc/workflow.py
- fix up batch.py script for LSF submission
- move all ganga stuff to batch_ganga.py
- add rand seed arg to workflow
- several other updates/changes (see commit log)
=> Development changes

python/hpsmc/workflow.py, python/jobs/beam_job.py
- Add optional beam parameters
- Sort list of jobs returned by workflow
=> Add optional beam parameter settings

CMakeLists.txt, python/hpsmc/batch.py, python/hpsmc/bsub.py, python/hpsmc/jsub.py, python/hpsmc/tools.py, python/hpsmc/workflow.py, scripts/hps-mc-bsub.in, scripts/hps-mc-jsub.in
- Add separate wrapper scripts for submitting to LSF and Auger
- Increase default job limit to 48 hours
- For now do not use the SLAC conditions db when submitting LSF jobs
- Print out event marker every 1000 events when running JobManager
=> Batch script updates and misc other stuff

CMakeLists.txt, python/hpsmc/tools.py
Reverts JeffersonLab/hps-mc#142
=> Revert "Updates to support offline conditions db usage"

python/hpsmc/job.py, python/hpsmc/tools.py
=> Updates for config support.

generators/egs5/config/src/lhe_exponential.f, generators/egs5/config/src/lhe_prompt.f, generators/egs5/config/src/lhe_rad.f, generators/egs5/config/src/lhe_uniform.f
ESG5 programs are updated by Takashi:
- lhe_rad.f: program for RAD smaple
- lhe_prompt.f: program for ap prompt sample
- lhe_exponential.f: program for ap displaced sample with "exponential-decay" model
- lhe_uniform.f: program for ap displaced sample with "uniform-decay" model
=> add egs5 scripts

python/jobs/beam_gen_to_slic_job.py
Update EGS5 component for automatic program name extension with beam energy.
=> Update EGS5 component

CMakeLists.txt, python/hpsmc/batch.py, python/hpsmc/file_checker.py, python/hpsmc/generators.py, python/hpsmc/help.py, python/hpsmc/job.py, python/hpsmc/job_store.py, python/hpsmc/job_template.py, python/hpsmc/parameters.py, python/hpsmc/run_params.py, python/hpsmc/script_db.py, python/hpsmc/tools.py, python/jobs/beam_gen_to_slic_job.py, python/jobs/rad_gen_to_slic_job.py, python/jobs/readout_recon_job.py, python/jobs/signal_beam_merge_to_recon_job.py, python/jobs/tritrig_beam_job.py, python/jobs/tritrig_gen_to_slic_job.py, python/jobs/wab_gen_to_slic_job.py, python/jobs/wab_sample_job.py
Python 2 is no longer supported at all.
=> Update hps-mc for Python 3 compatibility

CMakeLists.txt, python/hpsmc/batch.py, python/hpsmc/file_checker.py, python/hpsmc/generators.py, python/hpsmc/help.py, python/hpsmc/job.py, python/hpsmc/job_store.py, python/hpsmc/job_template.py, python/hpsmc/parameters.py, python/hpsmc/run_params.py, python/hpsmc/script_db.py, python/hpsmc/tools.py, python/jobs/beam_gen_to_slic_job.py, python/jobs/rad_gen_to_slic_job.py, python/jobs/readout_recon_job.py, python/jobs/signal_beam_merge_to_recon_job.py, python/jobs/tritrig_beam_job.py, python/jobs/tritrig_gen_to_slic_job.py, python/jobs/wab_gen_to_slic_job.py, python/jobs/wab_sample_job.py
Fix resolution of ptag output src in Auger.
Also includes a small fix in the template engine needed for Python 3.
Contains Python 3 fixes from #211 so should be merged after that PR.
=> Auger ptag fix (merge after #211)

examples/tritrig/job.json, examples/tritrig_gen_to_slic/job.json, python/jobs/tritrig_job.py
=> Update tritrig_job to 2019 and implement more ptags

python/hpsmc/tools.py, tools/stdhep-tools/src/random_sample.cc, tools/stdhep-tools/src/random_sample_usingInputEventsInOrder.cc
=> Forward nevents to random_sample if it was set

examples/tritrig_gen/job.json, python/hpsmc/generators.py, python/hpsmc/job.py, python/hpsmc/run_params.py
Also, fix some other minor bugs.
=> Allow target thickness for EGS5 to come from job parameters

examples/beam_gen/.hpsmc, examples/beam_gen/cleanup.sh, examples/beam_gen/job.json, examples/beam_gen/job.json.tmpl, examples/beam_gen/jobs.json, examples/beam_gen/mkjobs.sh, examples/beam_gen/run.sh, examples/beam_gen/run_auger.sh, examples/beam_gen/run_local.sh, examples/beam_gen/vars.json, python/jobs/beam_gen_job.py
New job type for making beam bunch files from gen up to right before slic.
=> Add beam_gen job which will run beam to before slic

examples/ap_displaced_gen_to_slic/.hpsmc, examples/ap_displaced_gen_to_slic/cleanup.sh, examples/ap_displaced_gen_to_slic/job.json, examples/ap_displaced_gen_to_slic/job.json.tmpl, examples/ap_displaced_gen_to_slic/mkjobs.sh, examples/ap_displaced_gen_to_slic/run.sh, examples/ap_displaced_gen_to_slic/run_auger.sh, examples/ap_displaced_gen_to_slic/run_local.sh, examples/ap_displaced_gen_to_slic/vars.json, examples/ap_prompt_gen_to_slic/.hpsmc, examples/ap_prompt_gen_to_slic/cleanup.sh, examples/ap_prompt_gen_to_slic/job.json, examples/ap_prompt_gen_to_slic/job.json.tmpl, examples/ap_prompt_gen_to_slic/mkjobs.sh, examples/ap_prompt_gen_to_slic/run.sh, examples/ap_prompt_gen_to_slic/run_auger.sh, examples/ap_prompt_gen_to_slic/run_local.sh, examples/ap_prompt_gen_to_slic/vars.json, python/jobs/ap_displaced_gen_to_slic_job.py, python/jobs/ap_prompt_gen_to_slic_job.py
Add job scripts for both ap prompt and displaced from generation to slic.
Add examples of job running for both ap prompt and displaced from generation to slic.
=> Update ap job

python/hpsmc/tools.py
This is so you can use conditions_url in .hpsmc to set the location of the db you want to use.
=> Adding conditions_url to JavaTools and EvioToLcio

CMakeLists.txt, examples/simp/.hpsmc, examples/simp/job.json, examples/simp/run.sh, python/hpsmc/generators.py, python/hpsmc/tools.py, python/jobs/simp_job.py, tools/stdhep-tools/src/lhe_tridents_displaceuni.cc
Discovered a few issues with the simp job and example. This fixes them and gets the example working and fixes the issues with the configuration of MadGraph5. I also added a new stdhep-tool to make uniformly distributed vtx in the z position rather than exponential.
=> Simp job debugging

examples/slic_to_anaMC/.hpsmc, examples/slic_to_anaMC/cleanup.sh, examples/slic_to_anaMC/job.json, examples/slic_to_anaMC/job.json.tmpl, examples/slic_to_anaMC/mkjobs.sh, examples/slic_to_anaMC/run.sh, examples/slic_to_anaMC/run_local.sh, examples/slic_to_anaMC/run_pool.sh, examples/slic_to_anaMC/run_slurm.sh, examples/slic_to_anaMC/subArray.sh, examples/slic_to_anaMC/sub_slurm.sh, examples/slic_to_anaMC/vars.json, python/jobs/slic_to_anaMC_job.py
This adds a new job for producing plots from mc truth information before readout biases the sample with the trigger.
=> Add slic_to_anaMC job for processing signal files for pre-trigger analysis

examples/slic/.hpsmc, examples/slic/hpsmc.cfg, examples/slic/job.json.tmpl, examples/slic/mkjobs.sh, examples/slic/run_swif.sh, python/hpsmc/batch.py, python/jobs/slic_job.py
=> Add Swif2 support

examples/moller_gen_to_slic/.hpsmc, examples/moller_gen_to_slic/cleanup.sh, examples/moller_gen_to_slic/job.json, examples/moller_gen_to_slic/run.sh, python/hpsmc/generators.py, python/jobs/moller_gen_to_slic_job.py
In job system, the component EGS5 is specified for beam processing. This update let it work for Moller processing. Besides, a job script and an example are developed for Moller from generation to SLIC.
=> update job system to be available for Moller processing

config/jlab_tongtong.cfg, examples/tritrig_pulser_overlay_to_recon/.hpsmc, examples/tritrig_pulser_overlay_to_recon/cleanup.sh, examples/tritrig_pulser_overlay_to_recon/job.json.tmpl, examples/tritrig_pulser_overlay_to_recon/mkjobs.sh, examples/tritrig_pulser_overlay_to_recon/pulser_files.txt, examples/tritrig_pulser_overlay_to_recon/run_swif.sh, examples/tritrig_pulser_overlay_to_recon/tritrig_files.txt, examples/tritrig_pulser_overlay_to_recon/vars.json, python/hpsmc/tools.py, python/jobs/signal_pulser_overlay_to_recon_job.py
The job system was updated to deal with MC for signal overlaid with pulser data.
Besides a job scrip was developed, python tools were updated, and configuration file was updated.
=> Update for pulse data merging

prod/tritrig_beam/comb/subArray.sh, prod/tritrig_beam/recon/subArray.sh, python/jobs/tritrig_beam_job.py
Some issues I came across while running the production scripts that I created.
=> prod dir bug fixes

tools/stdhep-tools/src/beam_coords.cc
This is a hotfix for a bug Emrys and I found.
=> Fix bug in stdhep rotations around x-axis

examples/ap_gen_to_slic/job.json, examples/ap_gen_to_slic/job.json.tmpl, examples/ap_gen_to_slic/vars.json, python/jobs/ap_gen_to_slic_job.py, python/jobs/ap_slic_job.py
Replace DisplaceTime with DisplaceUni in python/jobs.
=> switch to DisplaceUni

examples/examples_documentation.md, prod/prod.md, python/hpsmc/job_framework.md, python/jobs/job_scripts.md, tools/stdhep-tools/stdhep_tools.md
Some fixes and edits of the documentation
=> edit documentation

python/hpsmc/tools.py
fix to issue #325
Create link to fieldmaps directory to ensure that correct fieldmap is available for hps-java when running JavaTool or JobManager.
=> fix fieldmaps issue

python/hpsmc/tools.py
Reverts JeffersonLab/hps-mc#328
=> Revert "Revert "fix fieldmaps issue""

examples/.gitignore, examples/ap_gen_to_slic/run.sh, examples/beam_coords/run.sh, examples/beam_gen/run.sh, examples/beam_slic/run.sh, examples/data_cnv/run.sh, examples/fee_slic_to_recon/run.sh, examples/hpstr/run.sh, examples/moller_gen/run.sh, examples/rad_gen/run.sh, examples/readout_recon/run.sh, examples/run_examples.sh, examples/simp/run.sh, examples/slic_to_anaMC/run.sh, examples/tritrig_beam/run.sh, examples/tritrig_gen/run.sh, examples/tritrig_slic_full_chain/run.sh, examples/wab_gen_sample/run.sh, python/hpsmc/tools.py, python/jobs/tritrig_gen_to_beam_coords_job.py
I found a bug in the unzip component when running the examples. This is a fix to this (in `tools.py`). To make (future) testing more simple, I also included some small changes to the run scripts in `examples/`.
=> fix output files for unzip

examples/data_cnv/job.json, examples/readout_recon/job.json, python/hpsmc/tools.py, python/test/test_generators.py
adding an option to hpstr component to switch between GBL and KF tracks
=> Tracking option hpstr

python/hpsmc/job.py
as informed by the pycodestyle GitHub action
=> fix codestyle errors from cmp patch

examples/alignment/tracking/job.json.templ, python/hpsmc/__init__.py, python/hpsmc/_hadd.py, python/hpsmc/alignment/_apply.py, python/hpsmc/alignment/_parameter.py, python/hpsmc/alignment/_pattern.py, python/hpsmc/alignment/_pede.py, python/hpsmc/alignment/_util.py, python/hpsmc/job_template.py, python/jobs/misalign_job.py, python/jobs/pede_job.py, python/jobs/track_align_job.py, python/test/test_parameter_patterns.py
Whoops! Forgot to check the tests.
=> Pycodestyle patch

python/hpsmc/batch.py
This adds an option to batch jobs so we can tell the batch system if we have a minimum disk space requirement.
=> Add disk space requirement option to BatchSystem

prod/slac/mcprod_2021/tritrig/.hpsmc, prod/slac/mcprod_2021/tritrig/job.json, prod/slac/mcprod_2021/tritrig/job.json.tmpl, prod/slac/mcprod_2021/tritrig/mkjobs.sh, prod/slac/mcprod_2021/tritrig/run.sh, prod/slac/mcprod_2021/tritrig/run_slurm.sh, prod/slac/mcprod_2021/tritrig/vars.json, prod/slac/mcprod_2021/wab/.hpsmc, prod/slac/mcprod_2021/wab/job.json, prod/slac/mcprod_2021/wab/job.json.tmpl, prod/slac/mcprod_2021/wab/mkjobs.sh, prod/slac/mcprod_2021/wab/run.sh, prod/slac/mcprod_2021/wab/run_slurm.sh, prod/slac/mcprod_2021/wab/vars.json, python/jobs/tritrig_gen_to_slic_job.py, python/jobs/wab_gen_to_slic_job.py
=> Setup for mc production (gen step) at slac
